name: Build and tests workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}

  build:
    needs: [avoid_redundancy]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
      - name: Build app
        run: ./gradlew build -x test

  test:
    needs: [ avoid_redundancy ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Grant execute permissions for resource files
        run: chmod +x src/test/resources/wav_files/knife_30s_22050fr.wav
      - name: Grant execute permissions for resource files 2
        run: chmod +x src/test/resources/control_values/knife_30s_22050fr_MEAN

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Unit Tests
        run: ./gradlew test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/reports/tests/test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Unit Tests Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

